export function DesktopSvg({ className }: { className?: string }) {
  return (
    <svg
      width="24px"
      height="24px"
      viewBox="0 0 24 24"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <title>Desktop</title>
      <g
        id="Page-1"
        stroke="none"
        stroke-width="1"
        fill="none"
        fill-rule="evenodd"
      >
        <g id="Desktop">
          <rect
            id="Rectangle"
            fill-rule="nonzero"
            x="0"
            y="0"
            width="24"
            height="24"
          ></rect>
          <rect
            id="Rectangle"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            x="3"
            y="4"
            width="18"
            height="13"
            rx="2"
          ></rect>
          <line
            x1="7.5"
            y1="21"
            x2="16.5"
            y2="21"
            id="Path"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          ></line>
          <line
            x1="12"
            y1="17"
            x2="12"
            y2="21"
            id="Path"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          ></line>
        </g>
      </g>
    </svg>
  );
}
